### PR TITLE
 added ban command, recreated gitignore, added package-lock.json, and formatted package.json.

### PR DESCRIPTION
**Pull request by sourTaste000**
cringe code alert

### CODE REVIEW

**Comment by sourTaste000** [comment]
@humboldt123

**Comment by dominikaaaa** [comment]
this looks like anybody could ban anybody if they wanted ngl

**Comment by sourTaste000** [comment]
ah frick

**Comment by dominikaaaa** [comment]
also the ban reason doesn't work if it has spaces

**Comment by humboldt123** [comment]
I'll make my own pull with a ban command when I get on my pc

**Comment by humboldt123** [comment]
I will rewrite this myself, I already have one made.

**Pull request closed without merging**
