### PR TITLE
added roleinfo

### LINKED ISSUE #125: ;roleinfo
Gives information such as
- color
- if you have the following permissions (dyno lists useless ones)
  - Audit Log
  - Manage Roles/Server/Channels
  - Kick/Ban
  - Manage messages
  - Mention @ everyone and the such
Status
- high council vs lower council vs citizen

### PR DESCRIPTION
**Pull request by sourTaste000**
closes #125

### CODE REVIEW

**Comment by sourTaste000** [comment]
wait wtf why there is no changes

**Comment by sourTaste000** [comment]
should make it support names

**Comment by dominikaaaa** [comment]
I'd rather we not add more to the JS bot

**Comment by humboldt123** [comment]
There isn't a reason not to if it isn't an integral moderation feature.

**Comment by humboldt123** [comment]
I would like to point out the description is "Prepend Trans Rights~! :3 to your message" you might want to fix that.

**Comment by dominikaaaa** [comment]
> There isn't a reason not to if it isn't an integral moderation feature.

JS is :sick:

I already made a classloader

**Comment by humboldt123** [comment]
Yes but in the meantime this would be a useful feature to have.

**Comment by dominikaaaa** [comment]
Not really. There isn't really a reason to have such a command.

**Comment by dominikaaaa** [comment]
Outside of what I suggested

**Comment by sourTaste000** [comment]
bruh transfer #125 to bot-kt then

**Comment by sourTaste000** [comment]
https://github.com/kami-blue/bot-kt/issues/24

**Pull request closed without merging**
