### PR TITLE
cleaned up repo and added license

### PR DESCRIPTION
**Pull request by sourTaste000**
idk why the second commit is broken

### CODE REVIEW

**Comment by dominikaaaa** [comment]
why delete index.js

**Comment by sourTaste000** [comment]
there is a main.js

**Comment by sourTaste000** [comment]
honestly idk why theres both main.js and index.js

**Comment by humboldt123** [comment]
index is the file that runs when the bot starts that calls main so it cal save the logs

**Comment by sourTaste000** [comment]
cringe

**Comment by humboldt123** [comment]
unbased and unredpilled

**Pull request closed without merging**
