### PR TITLE
added uwu counter

### PR DESCRIPTION
**Pull request by sourTaste000**

### CODE REVIEW

**Comment by sourTaste000** [comment]
:tada: 100th pr

**Comment by sourTaste000** [comment]
#98

**Comment by sourTaste000** [comment]
@humboldt123

**Comment by humboldt123** [comment]
What

**Comment by humboldt123** [comment]
Have you tested it does it work?

**Comment by sourTaste000** [comment]
Yes it does work

**Comment by dominikaaaa** [comment]
I'll take a look later

**Comment by sourTaste000** [comment]
when merge !!!111!!1!1!!!11

**Comment by sourTaste000** [comment]
check #104

**Pull request closed without merging**
