### PR TITLE
Added anarchyservers

### PR DESCRIPTION
**Pull request by Finleyyy**
anarchyservers (or serverlists) command for people who can't search for themselves and have to ask in the Discord
(Probably bad code, I don't know JavaScript lol)

### CODE REVIEW

**Comment by humboldt123** [comment]
Firstly, what would the point of the command be, secondly 
```js
    aliases: [serverlists],
```
you need quotes around serverlists

**Comment by Finleyyy** [comment]
The point is that people like [this](https://i.imgur.com/h5dgExN.png) have something to click on.

**Comment by humboldt123** [comment]
Fix the issue with the code though

**Comment by humboldt123** [comment]
nvm lol you fixed it

**Pull request merged**
