### PR TITLE
added bigrat.js

### PR DESCRIPTION
**Pull request by TashDevCat**
added a ;bigrat command and fied the ip grabbing regex's (again)

### CODE REVIEW

**Comment by humboldt123** [comment]
Instead of setcolor BLACK set it to a hex colour code

**Comment by TashDevCat** [comment]
BLACK works and automatically makes it black lel, you dont need to write the exact hex, basic colors like RED ORANGE GREEN BLUE and also RANDOM are already there

**Comment by humboldt123** [comment]
Yes but use a hex color code like client.colors.kamiblue or whatever

**Comment by TashDevCat** [comment]
why? it doesnt change anything

**Comment by TashDevCat** [comment]
confuzin again

**Comment by TashDevCat** [comment]
nvm i see what you mean, sorry i was dumb i changed BLACK to client.colors.kamiblue

**Pull request closed without merging**
