### PR TITLE
made some changes and improvements

### PR DESCRIPTION
**Pull request by mattymatty97**
i wasn't able to test them as i've not he Bot tokens 😅 

in case of exceptions it will spit them out on Discord 😏

### CODE REVIEW

**Comment by wnuke** [comment]
You should be able to create your own bot tokens on discord, and test in a private server. But i'm not sure if thats what you mean.

**Comment by iBuyMountainDew** [comment]
@mattymatty97 Create your own bot application to test the KamiBlueBot with. That token stays locked in a box.

**Comment by mattymatty97** [comment]
i wasn't neither asking for the bot token nor willing to create another one.

i'm mattymatty from discord and i was helping qt earlier with making the bot working.

now i had time to fork, download and open with intellij to make the fixes/changes i was suggesting

**Comment by dominikaaaa** [comment]
i'll test this locally, later

**Comment by mattymatty97** [comment]
i guess i'll wait till qt gets awake to check those changes

**Comment by iBuyMountainDew** [comment]
Testing now

**Comment by iBuyMountainDew** [comment]
Done did.

**Pull request merged**
