### PR TITLE
maybe a fix?

### PR DESCRIPTION
**Pull request by sourTaste000**
i added try catch so it would output the err

### CODE REVIEW

**Comment by sourTaste000** [comment]
and formatted

**Comment by sourTaste000** [comment]
its not ready yet lmao

**Comment by dominikaaaa** [comment]
mfw

**Comment by sourTaste000** [comment]
i marked it as draft :joy:

**Comment by dominikaaaa** [comment]
well I needed the bot to stop crashing at the very least lmao

**Pull request merged**
